package com.idos.tictactoe.ui.theme

import androidx.compose.ui.graphics.Color

val Primery = Color(0xFFDF3C5F)
val BackGround = Color(0xFF224193)
val Secondery = Color(0xFF6F9BD1)


val md_theme_dark_primary = Color(0xFF134B5F)
val md_theme_dark_onPrimary = Color(0xFFA6EEFF)
val md_theme_dark_primaryContainer = Color(0xFF004788)
val md_theme_dark_onPrimaryContainer = Color(0xFFD5E3FF)
val md_theme_dark_secondary = Color(0xFFFFB787)
val md_theme_dark_onSecondary = Color(0xFF502400)
val md_theme_dark_secondaryContainer = Color(0xFF723600)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC7)
val md_theme_dark_tertiary = Color(0xFF4BE253)
val md_theme_dark_onTertiary = Color(0xFF003908)
val md_theme_dark_tertiaryContainer = Color(0xFF00530F)
val md_theme_dark_onTertiaryContainer = Color(0xFF72FF72)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6CF)
val md_theme_dark_outline = Color(0xFF8E9199)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF005EB2)
val md_theme_dark_surfaceTint = Color(0xFFA7C8FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)